version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  spring-boot-app:
    build:
      context: .
    container_name: demo-spring-boot-app-1
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    networks:
      - app-network

  vuejs-app:
    build:
      context: ./frontend
    container_name: demo-vuejs-app-1
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app
      - django-backend
    networks:
      - app-network

  django-backend:
    build:
      context: ./django-backend
    container_name: django-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
